version: '3.7'

services:
    db:
        platform: linux/x86_64
        image: mysql:latest
        volumes:
            - "./.mysql-data/db:/var/lib/mysql"
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: diploma
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
